Persistent logs #16
KTH-Software-Engineering-DD2480/ci pull request #33
Opened 2022-02-09 12:58 UTC by mantaur

fixes: #16 
Adds functionality to create and browse log files with PersistentLogs class. Contents of files is based on Log_entry class and can easily be modified.

2022-02-09 13:10 UTC, nolanderc requested changes
Make sure to add javadoc comments to any public functions

2022-02-09 13:10 UTC, nolanderc commented on src/main/java/ci/PersistentLogs.java
> +        }
Can we reuse the `all_files` method?

2022-02-09 13:10 UTC, nolanderc commented on src/main/java/ci/PersistentLogs.java
> +    }
Rather than including any non-log files (such as the README) which we are never going to use, how about we remove them instead? That is, we should make sure that only files matching the expected pattern `number_type.log` is included.

2022-02-09 13:10 UTC, nolanderc commented on src/main/java/ci/Log_entry.java
> +    }
Why do we need two different kinds of logs? What is the difference between them?

2022-02-09 13:12 UTC, nolanderc commented on src/main/java/ci/Log_entry.java
> +    public Test_status status;
We should also include the "console" output from gradle somewhere.

2022-02-09 13:48 UTC, nolanderc commented on src/main/java/ci/PersistentLogs.java
> +    }
By remove, I mean remove from the array, not disk.

2022-02-09 14:26 UTC, mantaur commented on src/main/java/ci/PersistentLogs.java
> +    }
Good point, whilst writing this function I alternated between all_files() and all_logs() which would not include README.md but I'll switch to the all_logs() since we prob won't want the README.md ever.

2022-02-09 14:33 UTC, mantaur commented on src/main/java/ci/Log_entry.java
> +    public Test_status status;
Sounds good, the simplest solution I see is to just add another string field and feed the console output to it.

2022-02-09 14:34 UTC, mantaur commented on src/main/java/ci/PersistentLogs.java
> +        }
Sounds good, will fix!

2022-02-09 14:36 UTC, nolanderc commented on src/main/java/ci/Log_entry.java
> +    }
What if we created a new `logs` directory for tests, and just deleted it in a cleanup step after tests are done? Come to think of it, it would be really nice if the `logs` directory was created for us if it does not already exist (even in the main implementation).

2022-02-09 14:53 UTC, mantaur commented on src/main/java/ci/Log_entry.java
> +    }
I'll try it out, perhaps I run into the same issues with deletion, but hopefully this folder will prevent clashing with the other logs

2022-02-09 14:56 UTC, nolanderc commented on src/main/java/ci/Log_entry.java
> +    }
Well, you have to make sure to close any streams/files before the test exits, as you always should. There are two attributes in JUnit: `@Before` and `@After`. You can use these to make a function run before/after each test in a class. You could try using these for deleting the directory.

2022-02-09 16:18 UTC, nolanderc commented on src/test/java/ci/PersistentLogsTest.java
> +    @BeforeEach
Make this `@AfterEach` so that we don't have any clutter after all tests are complete.

2022-02-09 16:59 UTC, nolanderc requested changes
Last comments \**pinky promise*\*

2022-02-09 16:59 UTC, nolanderc commented on src/main/java/ci/PersistentLogs.java
> +        }
Instead of catching exceptions here and silently failing, let the caller handle any errors so they can act accordingly.

2022-02-09 16:59 UTC, nolanderc commented on src/main/java/ci/PersistentLogs.java
> +        }
Same here. Although, in the case that the log entry does not exist, we could consider returning `null`

2022-02-09 16:59 UTC, nolanderc commented on src/main/java/ci/PersistentLogs.java
> +        else if (files_with_README.length == 1 && files_with_README[0].getName().equals("README.md")) return new File[0];
Do we need these special cases? How often will we not have any logs?

2022-02-09 19:36 UTC, mantaur commented on src/main/java/ci/PersistentLogs.java
> +        }
Good catch, this was probably done to satisfy the linter. Will do the proper "throws" rework

2022-02-09 19:43 UTC, mantaur commented on src/main/java/ci/PersistentLogs.java
> +        else if (files_with_README.length == 1 && files_with_README[0].getName().equals("README.md")) return new File[0];
It happens for every test, and the first run every time the repository is copied (but the logs aren't). Or in the case when the folder doesn't exist...

2022-02-10 09:02 UTC, nolanderc commented on src/test/java/ci/PersistentLogsTest.java
> +        }
Why do we silently fail if there's an exception? Wouldn't it be better if the test failed if something goes wrong (ie. don't catch the exception)?

2022-02-10 09:14 UTC, nolanderc approved these changes

2022-02-10 09:14 UTC, merged